AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Web Adapter Express.js Demo

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["node", "index.js"]
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      DockerTag: nodejs16-v1
      DockerContext: ./app
      Dockerfile: Dockerfile

Outputs:
  ExpressFunctionUrl:
    Description: "Function URL for Express app"
    Value: !GetAtt ExpressFunctionUrl.FunctionUrl
  ExpressFunction:
    Description: "Express Lambda Function ARN"
    Value: !GetAtt ExpressFunction.Arn
